Update src against 3.16

diff --git a/linux/src/Makefile b/linux/src/Makefile
--- a/linux/src/Makefile
+++ b/linux/src/Makefile
@@ -1,6 +1,7 @@
 #
 # Makefile for aescrypt
-# Copyright (C) 2007, 2008, 2009, 2013
+#
+# Copyright (C) 2022
 # Paul E. Jones <paulej@packetizer.com>
 #
 # This software is licensed as "freeware."  Permission to distribute
@@ -12,40 +13,31 @@
 # USE OF THIS SOFTWARE, EITHER DIRECTLY OR INDIRECTLY, INCLUDING, BUT
 # NOT LIMITED TO, LOSS OF DATA OR DATA BEING RENDERED INACCURATE.
 #
+# AES Crypt binaries are normally built using dynamic linking of libraries.
+# To statically link using GCC when building, use this command at the command
+# line:
+#    $ LDFLAGS=-static make
+#
 
 CC=gcc
+CFLAGS=-O3 -Wall -Wextra -pedantic -std=c11 -D_FILE_OFFSET_BITS=64
+AESCRYPT_OBJS=aescrypt.o aes.o sha256.o password.o keyfile.o util.o
+KEYGEN_OBJS=aescrypt_keygen.o keyfile.o password.o util.o
 
-#The below line is for debugging
-#CFLAGS=-I. -ggdb -Wall -D_FILE_OFFSET_BITS=64
-CFLAGS=-Wall -D_FILE_OFFSET_BITS=64 -static
-
-LIBS=
-
-#Uncomment the line below to compile on Mac
-#LIBS=-liconv
+# Linux does not need the iconv library included, though Mac and BSD do
+ifeq ($(shell uname -s), Linux)
+    LDLIBS=
+else
+    LDLIBS=-liconv
+endif
 
 all: aescrypt aescrypt_keygen
 
-aescrypt: aescrypt.o aes.o sha256.o password.o keyfile.o
-	$(CC) $(CFLAGS) $(LIBS) -o $@ $^
+aescrypt: $(AESCRYPT_OBJS)
+	$(CC) $(CFLAGS) $(LDLIBS) -o $@ $(AESCRYPT_OBJS) $(LDFLAGS)
 
-aescrypt_keygen: aescrypt_keygen.o password.o
-	$(CC) $(CFLAGS) $(LIBS) -o $@ $^
-
-test:
-	@$(CC) -DTEST -o sha.test sha256.c
-	@./sha.test
-	@#rm sha.test
-	@$(CC) -DTEST -o aes.test aes.c
-	@./aes.test
-	@#rm aes.test
-
-testfile: aescrypt
-	@echo "testing this 123..." > test.orig.txt
-	./aescrypt -e -p "praxis" test.orig.txt
-	@cp test.orig.txt.aes test.txt.aes
-	./aescrypt -d -p "praxis" test.txt.aes
-	cmp test.orig.txt test.txt
+aescrypt_keygen: $(KEYGEN_OBJS)
+	$(CC) $(CFLAGS) $(LDLIBS) -o $@ $(KEYGEN_OBJS) $(LDFLAGS)
 
 %.o: %.c %.h
 	$(CC) $(CFLAGS) -c $*.c
@@ -60,3 +52,67 @@ uninstall:
 
 clean:
 	rm -f *.o aescrypt aescrypt_keygen test* *test
+
+test: aescrypt
+	@$(CC) -DTEST -o sha.test sha256.c
+	@./sha.test
+	@rm sha.test
+	@$(CC) -DTEST -o aes.test aes.c
+	@./aes.test
+	@rm aes.test
+	# Encrypting and decrypting text files
+	# Test zero-length file
+	@cat /dev/null > test.orig.txt
+	@./aescrypt -e -p "praxis" test.orig.txt
+	@cp test.orig.txt.aes test.txt.aes
+	@./aescrypt -d -p "praxis" test.txt.aes
+	@cmp test.orig.txt test.txt
+	@rm test.orig.txt test.orig.txt.aes test.txt.aes test.txt
+	# Testing short file (one AES block)
+	@echo "Testing..." > test.orig.txt
+	@./aescrypt -e -p "praxis" test.orig.txt
+	@cp test.orig.txt.aes test.txt.aes
+	@./aescrypt -d -p "praxis" test.txt.aes
+	@cmp test.orig.txt test.txt
+	@rm test.orig.txt test.orig.txt.aes test.txt.aes test.txt
+	# Test password length boundary
+	# Test password length 0
+	@cat /dev/null >test.passwd.txt
+	@echo "Testing..." > test.txt
+	@# Expecting a failure here, but reflect opposite result code
+	@./aescrypt -e -p `cat test.passwd.txt` test.txt 2>/dev/null && \
+	    echo Password length test failed && \
+	    exit 1 || \
+	    true
+	@rm test.txt test.passwd.txt
+	# Test password length 1023
+	@cat /dev/null >test.passwd.txt
+	@for x in `seq 1 1023`; do printf X >>test.passwd.txt; done
+	@echo "Testing..." > test.txt
+	@./aescrypt -e -p `cat test.passwd.txt` test.txt
+	@rm test.txt.aes test.txt test.passwd.txt
+	# Test password length 1024
+	@cat /dev/null >test.passwd.txt
+	@for x in `seq 1 1024`; do printf X >>test.passwd.txt; done
+	@echo "Testing..." > test.txt
+	@./aescrypt -e -p `cat test.passwd.txt` test.txt
+	@rm test.txt.aes test.txt test.passwd.txt
+	# Test password length 1025
+	@cat /dev/null >test.passwd.txt
+	@for x in `seq 1 1025`; do printf X >>test.passwd.txt; done
+	@echo "Testing..." > test.txt
+	@# Expecting a failure here, but reflect opposite result code
+	@./aescrypt -e -p `cat test.passwd.txt` test.txt 2>/dev/null && \
+	    echo Password length test failed && \
+	    exit 1 || \
+	    true
+	@rm test.txt test.passwd.txt
+	# Testing longer file
+	@cat /dev/null >test.orig.txt
+	@for i in `seq 1 50000`; do echo "This is a test" >>test.orig.txt; done
+	@./aescrypt -e -p "praxis" test.orig.txt
+	@cp test.orig.txt.aes test.txt.aes
+	@./aescrypt -d -p "praxis" test.txt.aes
+	@cmp test.orig.txt test.txt
+	@rm test.orig.txt test.orig.txt.aes test.txt.aes test.txt
+	@echo All file encryption tests passed
